version: "3"
services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: php:latest
    working_dir: /application
    depends_on:
      - db
    volumes:
      - .:/application
      - ./docker/php/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    networks:
      bet:
        ipv4_address: 10.16.0.2

  nginx:
    image: nginx:alpine
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      bet:
        ipv4_address: 10.16.0.3

  db:
    image: mysql
    volumes:
      - ./../data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bet
      - MYSQL_HOST=127.0.0.1
    networks:
      bet:
        ipv4_address: 10.16.0.4

networks:
  bet:
    external: true
