account_actions:
    resource: '../../src/Account/Http/Action/'
    type: annotation

bet_controllers:
    resource: '../../src/Bet/Http/Action/'
    type: annotation

kernel:
    resource: ../../framework/Kernel.php
    type: annotation
